/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
        h1: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        h2: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        h3: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-sm': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'label-md': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Use CSS variables for theme support
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        'on-background': 'var(--color-foreground)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant': 'var(--color-surface-container)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': '#0053db',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        secondary: 'var(--color-secondary)',
        'on-secondary': '#ffffff',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        tertiary: '#525657',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6b6e70',
        'on-tertiary-container': '#eff1f3',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        border: 'var(--color-border)',
        input: 'var(--color-border)',
        ring: 'var(--color-primary)',
        destructive: 'var(--color-error)',
        'destructive-foreground': 'var(--color-on-error)',
        muted: 'var(--color-muted)',
        'muted-foreground': 'var(--color-muted-foreground)',
        accent: '#2563eb',
        'accent-foreground': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        'container-max': '1440px',
        'sidebar-width': '260px',
      },
    },
  },
  plugins: [
    function({ addVariant }) {
      addVariant('dark', '.dark &');
    }
  ],
};
