/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
        h1: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        h2: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        h3: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'body-sm': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        'label-md': ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
      },
      colors: {
        background: '#faf8ff',
        foreground: '#131b2e',
        'on-background': '#131b2e',
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434655',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'surface-tint': '#0053db',
        primary: '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        tertiary: '#525657',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6b6e70',
        'on-tertiary-container': '#eff1f3',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        border: '#c3c6d7',
        input: '#c3c6d7',
        ring: '#004ac6',
        destructive: '#ba1a1a',
        'destructive-foreground': '#ffffff',
        muted: '#f2f3ff',
        'muted-foreground': '#434655',
        accent: '#2563eb',
        'accent-foreground': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        'container-max': '1440px',
        'sidebar-width': '260px',
      },
    },
  },
  plugins: [],
};
